<?
/*add_action('acf/init', function () {
	if (!function_exists('acf_add_local_field_group')) {
		return;
	}

	acf_add_local_field_group(
		array(
			'key' => 'group_64ebf81583bqq',
			'title' => 'Casino extra fields',
			'fields' => array(
				array(
					'key' => 'field_64ebf81583321',
					'label' => 'Bonus fields',
					'name' => 'bonus_fields',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'wpml_cf_preferences' => 0,
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_64ebf81583b12',
							'label' => 'Bonus title',
							'name' => 'bonus_title',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
							'wpml_cf_preferences' => 2,
						),
						array(
							'key' => 'field_65aeab19da25c',
							'label' => 'Bonus Link',
							'name' => 'bonus_link',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_65aead37da25d',
							'label' => 'Promo Code',
							'name' => 'promo_code',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_64ebf81583b13',
							'label' => 'Bonus description',
							'name' => 'bonus_description',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
							'wpml_cf_preferences' => 2,
						),
						array(
							'key' => 'field_64ebf81583b14',
							'label' => 'For whom',
							'name' => 'for_whom',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 0,
							'choices' => array(
								'val1' => __('New Customer', 'mercury-child'),
								'val2' => __('Existing Customer', 'mercury-child'),
							),
							'default_value' => 'val1',
							'return_format' => 'label',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_64ebf81583b15',
							'label' => 'Form',
							'name' => 'form',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 0,
							'choices' => array(
								'val1' => __('Free Spins', 'mercury-child'),
								'val2' => __('Cash Bonus', 'mercury-child'),
								'val3' => __('Prize', 'mercury-child'),
								'val4' => __('Bonus Points', 'mercury-child'),
								'val5' => __('Cash Bonus + Free Spins', 'mercury-child'),
							),
							'default_value' => 'val1',
							'return_format' => 'label',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_64ebf81583b16',
							'label' => 'Type',
							'name' => 'type',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 0,
							'choices' => array(
								'val1' => __('No Deposit Bonus', 'mercury-child'),
								'val2' => __('Deposit Bonus', 'mercury-child'),
								'val3' => __('No Risk Bet', 'mercury-child'),
								'val4' => __('Bet & Get', 'mercury-child'),
								'val5' => __('Accumulator Bet Bonus', 'mercury-child'),
								'val6' => __('Cashback', 'mercury-child'),
								'val7' => __('Boosted Odds', 'mercury-child'),
								'val8' => __('Betting App Offers', 'mercury-child'),
								'val9' => __('Loyalty Programme', 'mercury-child'),
								'val10' => __('Refer a Friend Bonus', 'mercury-child'),
								'val11' => __('Birthday Bonus', 'mercury-child'),
								'val12' => __('Contests & Prize Draws', 'mercury-child'),
								'val13' => __('Other Promotions', 'mercury-child'),
							),
							'default_value' => 'val1',
							'return_format' => 'label',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_64ebf81583b17',
							'label' => 'Term',
							'name' => 'term',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 0,
							'choices' => array(
								'val1' => '-',
								'val2' => __('Limited', 'mercury-child'),
							),
							'default_value' => 'val1',
							'return_format' => 'label',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_64ebf81583b18',
							'label' => 'Best bonus',
							'name' => 'best_bonus',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 0,
							'choices' => array(
								'val1' => '-',
								'val2' => __('Yes', 'mercury-child'),
								'val3' => __('No', 'mercury-child'),
							),
							'default_value' => 'val1',
							'return_format' => 'label',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_64ebf81583435',
							'label' => 'Cashback',
							'name' => 'cashback',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 0,
							'choices' => array(
								'val1' => '-',
								'val2' => __('Yes', 'mercury-child'),
								'val3' => __('No', 'mercury-child'),
							),
							'default_value' => 'val1',
							'return_format' => 'label',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_64ebf81583b20',
							'label' => 'Birthday bonus',
							'name' => 'birthday_bonus',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 0,
							'choices' => array(
								'val1' => '-',
								'val2' => __('Yes', 'mercury-child'),
								'val3' => __('No', 'mercury-child'),
							),
							'default_value' => 'val1',
							'return_format' => 'label',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_64ebf81583b21',
							'label' => 'Best for',
							'name' => 'best_for',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 2,
							'default_value' => __('Best bonus online', 'mercury-child'),
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_64ebf81583b22',
							'label' => 'Trusted',
							'name' => 'trusted',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'wpml_cf_preferences' => 0,
							'message' => '',
							'default_value' => 1,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
					),
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'casino',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
			'show_in_rest' => 0,
			'acfml_field_group_mode' => 'advanced',
		)
	);
});*/
