<?
function getReviewListGroupParams($postfix)
{
  return array(
    'key' => 'group_65d62feb546ca' . $postfix,
    'title' => 'Review List',
    'fields' => array(
      array(
        'key' => 'field_65d64435026b5' . $postfix,
        'label' => 'Settings',
        'name' => 'casino_selection_group',
        'aria-label' => '',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(

          array(
            'key' => 'field_662a8c530400a' . $postfix,
            'label' => 'Post Type',
            'name' => 'post_type',
            'aria-label' => '',
            'type' => 'button_group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'casino' => 'Casino',
              'bookmaker' => 'Bookmaker',
            ),
            'default_value' => 'casino',
            'return_format' => 'value',
            'allow_null' => 0,
            'layout' => 'horizontal',
          ),
          array(
            'key' => 'field_668d98c9ce1ab' . $postfix,
            'label' => 'Bonus Category',
            'name' => 'bonus_category',
            'aria-label' => '',
            'type' => 'taxonomy',
            'instructions' => 'Bonus category for all items in list',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'taxonomy' => 'bonus-category',
            'add_term' => 0,
            'save_terms' => 0,
            'load_terms' => 0,
            'return_format' => 'id',
            'field_type' => 'select',
            'allow_null' => 1,
            'bidirectional' => 0,
            'multiple' => 0,
            'bidirectional_target' => array(),
          ),
          array(
            'key' => 'field_66676a0fa927c' . $postfix,
            'label' => 'Show License & AR text for listing',
            'name' => 'show_license_ar_text_for_listing',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => 'Will be shown under the title or instead of it if it is not there.
  You can customize the text by going to Template Settings ->Regulator, License & Age Rating settings (Casino/Bookmaker Listing)',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 1, //$postfix == '_block' ? 0 : 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
          array(
            'key' => 'field_65f0a27ba39da' . $postfix,
            'label' => 'Disable pagination',
            'name' => 'disable_pagination',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => 'Attention! The entire list will be displayed at once.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
          array(
            'key' => 'field_65d62febc0fdc' . $postfix,
            'label' => 'Review List',
            'name' => 'casino_list',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'layout' => 'row',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => 'Add Row',
            'rows_per_page' => 20,
            'sub_fields' => array(
              array(
                'key' => 'field_76fgkj3056wak',
                'label' => 'Custom Title',
                'name' => 'custom_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
              ),
              array(
                'key' => 'field_65d6302ac0fdd' . $postfix,
                'label' => 'Casino',
                'name' => 'casino_id',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_662a8c530400a' . $postfix,
                      'operator' => '==',
                      'value' => 'casino',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'post_type' => array(
                  0 => 'casino',
                ),
                'post_status' => array(
                  0 => 'publish',
                  1 => 'draft',
                ),
                'taxonomy' => '',
                'return_format' => 'id',
                'multiple' => 0,
                'allow_null' => 0,
                'bidirectional' => 0,
                'ui' => 1,
                'bidirectional_target' => array(),
                'parent_repeater' => 'field_65d62febc0fdc' . $postfix,
              ),
              array(
                'key' => 'field_662a8c920400b' . $postfix,
                'label' => 'Bookmaker',
                'name' => 'bookmaker_id',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                  array(
                    array(
                      'field' => 'field_662a8c530400a' . $postfix,
                      'operator' => '==',
                      'value' => 'bookmaker',
                    ),
                  ),
                ),
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'post_type' => array(
                  0 => 'bookmaker',
                ),
                'post_status' => array(
                  0 => 'publish',
                  1 => 'draft',
                ),
                'taxonomy' => '',
                'return_format' => 'id',
                'multiple' => 0,
                'allow_null' => 0,
                'bidirectional' => 0,
                'ui' => 1,
                'bidirectional_target' => array(),
                'parent_repeater' => 'field_65d62febc0fdc' . $postfix,
              ),
              array(
                'key' => 'field_668d9b8bce1ad' . $postfix,
                'label' => 'Bonus Category',
                'name' => 'bonus_category',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'taxonomy' => 'bonus-category',
                'add_term' => 0,
                'save_terms' => 0,
                'load_terms' => 0,
                'return_format' => 'id',
                'field_type' => 'select',
                'allow_null' => 1,
                'bidirectional' => 0,
                'multiple' => 0,
                'bidirectional_target' => array(),
                'parent_repeater' => 'field_65d62febc0fdc'  . $postfix,
              ),
              array(
                'key' => 'field_65f0d9d97924f' . $postfix,
                'label' => 'Hide footer',
                'name' => 'hide_footer',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => 'Hide the inner bottom part of the card',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'parent_repeater' => 'field_65d62febc0fdc' . $postfix,
              ),

            ),
          ),

          array(
            'key' => 'field_66fb48ceb3cc3'  . $postfix,
            'label' => 'Ref Modal',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
          ),
          array(
            'key' => 'field_66fb135fddf00' . $postfix,
            'label' => 'Ref Items Shows',
            'name' => 'ref_items_shows',
            'aria-label' => '',
            'type' => 'range',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 5,
            'min' => 1,
            'max' => 5,
            'step' => '',
            'prepend' => '',
            'append' => '',
          ),
          array(
            'key' => 'field_66fb4850b3cbf' . $postfix,
            'label' => 'Modal Title',
            'name' => 'ref_modal_title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
          ),
          array(
            'key' => 'field_66fb4854b3cc0' . $postfix,
            'label' => 'Modal Subtitle',
            'name' => 'ref_modal_subtitle',
            'aria-label' => '',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'acfe_textarea_code' => 0,
            'maxlength' => '',
            'rows' => 3,
            'placeholder' => '',
            'new_lines' => '',
          ),
          array(
            'key' => 'field_66fb485fb3cc1' . $postfix,
            'label' => 'Hide Modal Title',
            'name' => 'hide_ref_modal_title',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
          array(
            'key' => 'field_66fb489ab3cc2' . $postfix,
            'label' => 'Hide Modal Subtitle',
            'name' => 'hide_ref_modal_subtitle',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
          ),

        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
  );
}
