name: Build Frontend
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.2

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: cd ./wp/wp-content/themes/mercury-child/frontend && yarn

      - name: Compile build
        run: cd ./wp/wp-content/themes/mercury-child/frontend && yarn run build

      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          committer_name: Build Bot
          message: 'bot: build frontend'
        env:
          GITHUB_TOKEN: ${{ secrets.GTH_TOKEN }} # This gets generated automatically
